# Generated by Django 4.2.4 on 2023-08-21 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=128)),
                ('eventid', models.IntegerField()),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('title', models.CharField(max_length=100)),
                ('all_day', models.BooleanField()),
                ('r_rule', models.CharField(max_length=50)),
                ('notes', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='TodoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=128)),
                ('itemid', models.IntegerField()),
                ('title', models.CharField(max_length=100)),
                ('category', models.IntegerField()),
                ('dueDate', models.DateTimeField()),
                ('totalTime', models.IntegerField()),
            ],
        ),
    ]
