# Generated by Django 4.2.4 on 2023-08-21 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='all_day',
            new_name='allDay',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='end_date',
            new_name='endDate',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='r_rule',
            new_name='rRule',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='start_date',
            new_name='startDate',
        ),
    ]
