# Generated by Django 4.2.4 on 2023-08-21 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_rename_all_day_event_allday_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='notes',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='rRule',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
