# Generated by Django 4.2.4 on 2023-08-25 01:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_alter_event_notes_alter_event_rrule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='eventid',
        ),
    ]
