# Generated by Django 4.2.4 on 2023-08-25 01:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_remove_event_eventid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todoitem',
            name='itemid',
        ),
    ]
