# Generated by Django 4.2.4 on 2023-08-26 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_alter_event_rrule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='rRule',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
