# Generated by Django 4.2.4 on 2023-09-05 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_alter_event_exdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoitem',
            name='category',
            field=models.CharField(max_length=10),
        ),
    ]
