# Generated by Django 4.2.4 on 2023-09-10 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_alter_todoitem_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='autoScheduled',
            field=models.BooleanField(default=False),
        ),
    ]
