# Generated by Django 4.2.4 on 2023-09-11 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0014_todoitem_timeleft'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='todoID',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
